[2021-03-17 16:09:23,683] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: PostgresOperator_dag.create_table 2021-03-17T16:09:22.842919+00:00 [queued]>
[2021-03-17 16:09:23,708] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: PostgresOperator_dag.create_table 2021-03-17T16:09:22.842919+00:00 [queued]>
[2021-03-17 16:09:23,710] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 16:09:23,711] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-17 16:09:23,712] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 16:09:23,724] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_table> on 2021-03-17T16:09:22.842919+00:00
[2021-03-17 16:09:23,729] {standard_task_runner.py:52} INFO - Started process 46 to run task
[2021-03-17 16:09:23,736] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'PostgresOperator_dag', 'create_table', '2021-03-17T16:09:22.842919+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpym6kzfhc', '--error-file', '/tmp/tmpgai1od45']
[2021-03-17 16:09:23,738] {standard_task_runner.py:77} INFO - Job 16: Subtask create_table
[2021-03-17 16:09:23,800] {logging_mixin.py:104} INFO - Running <TaskInstance: PostgresOperator_dag.create_table 2021-03-17T16:09:22.842919+00:00 [running]> on host c065581206d5
[2021-03-17 16:09:23,874] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=PostgresOperator_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2021-03-17T16:09:22.842919+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-17T16:09:22.842919+00:00
[2021-03-17 16:09:23,877] {postgres.py:69} INFO - Executing: CREATE TABLE IF NOT EXISTS user_table(
            id integer NOT NULL, email VARCHAR, active BOOLEAN
            );
[2021-03-17 16:09:23,895] {base.py:74} INFO - Using connection to: id: postgresql. Host: db, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2021-03-17 16:09:23,901] {dbapi.py:180} INFO - Running statement: CREATE TABLE IF NOT EXISTS user_table(
            id integer NOT NULL, email VARCHAR, active BOOLEAN
            );, parameters: None
[2021-03-17 16:09:23,904] {dbapi.py:186} INFO - Rows affected: -1
[2021-03-17 16:09:23,908] {postgres.py:73} INFO - NOTICE:  relation "user_table" already exists, skipping

[2021-03-17 16:09:23,927] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=PostgresOperator_dag, task_id=create_table, execution_date=20210317T160922, start_date=20210317T160923, end_date=20210317T160923
[2021-03-17 16:09:23,964] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-17 16:09:23,992] {local_task_job.py:146} INFO - Task exited with return code 0
