[2021-03-15 17:28:12,525] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: PostgresOperator_dag.create_table 2021-03-15T17:28:10.945605+00:00 [queued]>
[2021-03-15 17:28:12,538] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: PostgresOperator_dag.create_table 2021-03-15T17:28:10.945605+00:00 [queued]>
[2021-03-15 17:28:12,540] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-15 17:28:12,541] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-15 17:28:12,542] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-15 17:28:12,559] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_table> on 2021-03-15T17:28:10.945605+00:00
[2021-03-15 17:28:12,564] {standard_task_runner.py:52} INFO - Started process 44 to run task
[2021-03-15 17:28:12,571] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'PostgresOperator_dag', 'create_table', '2021-03-15T17:28:10.945605+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmprscs1oqt', '--error-file', '/tmp/tmpueo8wv0w']
[2021-03-15 17:28:12,572] {standard_task_runner.py:77} INFO - Job 12: Subtask create_table
[2021-03-15 17:28:12,630] {logging_mixin.py:104} INFO - Running <TaskInstance: PostgresOperator_dag.create_table 2021-03-15T17:28:10.945605+00:00 [running]> on host 802d9e669445
[2021-03-15 17:28:12,680] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=PostgresOperator_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2021-03-15T17:28:10.945605+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-15T17:28:10.945605+00:00
[2021-03-15 17:28:12,681] {postgres.py:69} INFO - Executing: CREATE TABLE IF NOT EXISTS user_table(
            id integer NOT NULL, email VARCHAR, active BOOLEAN
            );
[2021-03-15 17:28:12,692] {base.py:74} INFO - Using connection to: id: postgresql. Host: db, Port: 5432, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2021-03-15 17:28:12,697] {dbapi.py:180} INFO - Running statement: CREATE TABLE IF NOT EXISTS user_table(
            id integer NOT NULL, email VARCHAR, active BOOLEAN
            );, parameters: None
[2021-03-15 17:28:12,699] {dbapi.py:186} INFO - Rows affected: -1
[2021-03-15 17:28:12,701] {postgres.py:73} INFO - NOTICE:  relation "user_table" already exists, skipping

[2021-03-15 17:28:12,713] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=PostgresOperator_dag, task_id=create_table, execution_date=20210315T172810, start_date=20210315T172812, end_date=20210315T172812
[2021-03-15 17:28:12,747] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-15 17:28:12,787] {local_task_job.py:146} INFO - Task exited with return code 0
